phpapache:
    build: ./php-on-apache-container
    dockerfile: Dockerfile
    ports:
        - "8080:80"
    volumes:
        - dev:/var/www
    links:
        - db
    container_name: php
    environment:
      VIRTUAL_HOST: php.docker
db:
    build: ./mysql-container
    dockerfile: Dockerfile
    volumes:
        - mysql:/usr/local/mysql/data
    ports:
        - "3307:3306"
    container_name: mysql
